CREATE TABLE venistasia_saves (
      id INT AUTO_INCREMENT PRIMARY KEY,
      player_id VARCHAR(64) NOT NULL UNIQUE,
      state_json LONGTEXT NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

